### ISSUE TITLE
Lack of interface for the service

### ISSUE THREAD

**Issue by aandrey1993** [jekajeayjo/crazy_monkey_bank#1]
Добрый день.  Меня зовут Андрей)) Мы с @meiendorf  делаем ревью тестового задания. По возникшим вопросам будем открывать тикеты. Постарайся на них дать ответ, либо внести соответствующие правки в код.

## Описание 
Для правильной организации `dependency injection`, для всех сервисов, репозитариях, необходимо определить interface, описывающие открытые методы которые он предоставляет. При выполнении Inject, указывается interface, вместо реализации. Spring сам найдет соответсвующий bin для использования.

## Задача
1. Добавить `interface` для сервиса `AccountsServiceImpl`, добавить наследование от сервиса
2. DI сделать через конструктор, используя аннотацию `@Autowiered`
3. Везде где используется внедрение какого-нибудь сервиса, добавить модификаторы `private final`
![изображение](https://user-images.githubusercontent.com/49781313/123437999-f1b8bb80-d5d8-11eb-8dcb-4dc0e51c5efe.png)

**Comment by Meiendorf** [comment]
Done by 9ae27985bf936e57b5e5d93592d0757770ca2b87

**Comment by aandrey1993** [comment]
Сделаны все необходимые исправления. Вопрос закрыт
