### ISSUE TITLE
Procedure call is executed in the service

### ISSUE THREAD

**Issue by aandrey1993** [jekajeayjo/crazy_monkey_bank#2]
## Описание
Код разделается на слои контроллер, сервис, репозиторий. Считается плохой практикой когда обращение к базе выполняется из сервиса. Для этого есть слой DAO.

## Задача
Перенести вызов процедуры на уровне репозитория. Можешь сделать отдельный репозиторий для этого, в нем будет логика определения `sqlServerDataSource`, вызов процедуры, считывание данных. Также обрати внимание на то что данные из процедуры нужно считать в какую-то модель, а не в hashmap

**Comment by Meiendorf** [comment]
Done by https://github.com/jekajeayjo/crazy_monkey_bank/commit/ebc615f72cb2498cf75eed9779ef20a19538a0f3

**Comment by aandrey1993** [comment]
Для вызова процедуры был заведен отдельный репозиторий `AccountJdbcRepository`. Для него присутствует и `interface`. Тикет закрываю.
