### ISSUE TITLE
Fetch from db into DTO instead of linked list

### ISSUE THREAD

**Issue by Meiendorf** [jekajeayjo/crazy_monkey_bank#3]
Добрый день.
Меня зовут Роман, мы, совместно с @aandrey1993 проводим ревью тестового задания.
По ходу ревью будем открывать тикеты с вопросами/предложениями для улучшения кода.

## Описание
Сейчас, данные из хранимой процедуры считываются как `Map` и непонятно, какая структура у получаемых данных, в коде ими сложно оперировать.  Так же, в swagger нет структуры ответа API вызова.  

## Задача
1. Считывать данные, полученные от процедуры, в DTO.
Для этого можно использовать, к примеру, `NamedJdbcTemplate`, вместе `SimpleJdbcCall`: 
```java
Map<String, Object> params = new HashMap<String, Object>() {{
    put("id", "1");
}};
new NamedParameterJdbcTemplate(sqlServerDataSource).query("getAccoutById :id", params, rs -> {
    rs.getString("acc");
});
```
2. Добавить в swagger структура ответа api, основываясь на созданном DTO.

**Comment by aandrey1993** [comment]
Обрати внимание что `AccountDto` в коде есть, но он нигде не используется сейчас. Можно его заполнять данными из процедуры. 

Хотя в реальных проектах, правильнее завести один объект для данных которые возвращаются из контроллера, другой объект для считывания из процедуры.

**Comment by Meiendorf** [comment]
Done by https://github.com/jekajeayjo/crazy_monkey_bank/commit/ebc615f72cb2498cf75eed9779ef20a19538a0f3
