### ISSUE TITLE
Check if a user exists with the received id

### ISSUE THREAD

**Issue by aandrey1993** [jekajeayjo/crazy_monkey_bank#4]
Подскажи, какая логика заложена в данном участке кода ?

![изображение](https://user-images.githubusercontent.com/49781313/123439001-f6ca3a80-d5d9-11eb-9a09-8c7f57f2c86a.png)

Если таким образом выполняется проверка что пользователь с полученным Id существует, такой подход немного не правильный.  JPA дает тебе специальный инструмент для этого: `existsById`.          
Например:
```java
if(userRepository.existsById(id)) {
   return null;
}
```

## Задача
Переписать проверку если по полученному Id существует пользователь. В случае если пользователь не найден, выбросить специальную ошибку, которая будет обработана на уровне контроллера. (Можно вернуть http код 404, либо вернуть код и описание ошибки).

**Comment by Meiendorf** [comment]
Kind of done by https://github.com/jekajeayjo/crazy_monkey_bank/commit/9ae27985bf936e57b5e5d93592d0757770ca2b87#diff-9e0f7ea7ccfd5988c00b4d5a80cc8621f24b14d31bd20f32b7b991c4e160f73dR52

Вместо метода `existById()` использовано `.findById().isPresent()`. Тоже нормально, лучше, чем было.

**Comment by aandrey1993** [comment]
Согласен с @Meiendorf что можно было использовать подходу указанный в тикете `existById`. С `isPresent` тоже будет работать, но выглядит как лишнее действие.

Тикет закрываю
